/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;
import data.Persistencia;
import domain.Carnivoro;
import domain.Especie;
import domain.Herbivoro;
import domain.Pais;
import domain.Sector;
import domain.TipoAlimentacion;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
/**
 *
 * @author pop
 */
public class AltaAnimalViewModel extends javax.swing.JFrame {

    /**
     * Creates new form AltaAnimalViewModel
     */
    public AltaAnimalViewModel() {
        initComponents();
        getAlimentacion();
        getSector();
    }
    private void getSector(){
        ArrayList<Sector> sectores = Persistencia.getSectores();
        Vector<String> sectorString = new Vector<>();
        for(Sector sector: sectores){
            sectorString.add(sector.toString());
        }
        comboBoxSector.setModel(new DefaultComboBoxModel(sectorString));
    }
    private void getAlimentacion(){
        Vector<TipoAlimentacion> alimentacion = new Vector<>();
        alimentacion.add(TipoAlimentacion.CARNIVORO);
        alimentacion.add(TipoAlimentacion.HERBIVORO);
        alimentacion.add(TipoAlimentacion.OMNIVORO);
        Vector<String> alimentacionString = new Vector<>();
        for(TipoAlimentacion tipoAlimentacion : alimentacion){
            alimentacionString.add(tipoAlimentacion.toString());
        }
        comboBoxAlimentacion.setModel(new DefaultComboBoxModel<>(alimentacionString));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        labelNombre = new javax.swing.JLabel();
        buttonAgregar = new javax.swing.JButton();
        buttonEliminar = new javax.swing.JButton();
        textFieldNombre = new javax.swing.JTextField();
        comboBoxAlimentacion = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        textFieldCodigo = new javax.swing.JTextField();
        labelNombre1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textFieldValorFijo = new javax.swing.JTextField();
        labelNombre2 = new javax.swing.JLabel();
        comboBoxSector = new javax.swing.JComboBox<>();
        jLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textFieldPeso = new javax.swing.JTextField();
        jPeso = new javax.swing.JLabel();
        textFieldEdad1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textFieldNombrePais1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelNombre.setText("Nombre");

        buttonAgregar.setText("Agregar");
        buttonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAgregarActionPerformed(evt);
            }
        });

        buttonEliminar.setText("Eliminar");
        buttonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEliminarActionPerformed(evt);
            }
        });

        comboBoxAlimentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxAlimentacionActionPerformed(evt);
            }
        });

        jLabel1.setText("Alimentacion");

        textFieldCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCodigoActionPerformed(evt);
            }
        });

        labelNombre1.setText("Pais");

        jLabel2.setText("nombre");

        jLabel3.setText("codigo");

        textFieldValorFijo.setEnabled(false);
        textFieldValorFijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldValorFijoActionPerformed(evt);
            }
        });

        labelNombre2.setText("Sector");

        comboBoxSector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxSectorActionPerformed(evt);
            }
        });

        jLabel.setToolTipText("");
        jLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel.setEnabled(false);
        jLabel.setFocusable(false);
        jLabel.setName(""); // NOI18N

        jLabel4.setText("Edad");

        textFieldPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldPesoActionPerformed(evt);
            }
        });

        jPeso.setText("Peso");

        textFieldEdad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldEdad1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Valor fijo");

        textFieldNombrePais1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNombrePais1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textFieldValorFijo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(textFieldEdad1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jPeso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textFieldPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNombre2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboBoxSector, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(buttonEliminar)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelNombre1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel2))
                                    .addComponent(jLabel1)))
                            .addComponent(jLabel))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(comboBoxAlimentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(textFieldNombrePais1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(textFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(buttonAgregar)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNombre)
                            .addComponent(textFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(textFieldPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPeso)
                            .addComponent(textFieldEdad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboBoxSector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNombre2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboBoxAlimentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNombre1)
                            .addComponent(jLabel2)
                            .addComponent(textFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textFieldNombrePais1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textFieldValorFijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAgregar)
                    .addComponent(buttonEliminar))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAgregarActionPerformed
        String nombreAnimal = textFieldNombre.getText();
        Sector sector = null;
        ArrayList<Sector> sectores = Persistencia.getSectores();
        sector = sectores.get(comboBoxSector.getSelectedIndex());
        
        String paisNombre = textFieldNombrePais1.getText();
        String paisID = textFieldCodigo.getText();
        TipoAlimentacion alimentacion = null;
        int edad = 0;
        double peso = 0;
        try{
            String pesostring = textFieldEdad1.getText();
            String varString = textFieldPeso.getText();
            peso = Float.parseFloat(varString);
            edad = Integer.parseInt(pesostring);
        }catch (java.lang.Exception e){
            edad = 0;
            peso = 0;
        }
        Especie especie = null;
        Pais pais = new Pais(paisNombre, paisID);
        switch (comboBoxAlimentacion.getSelectedIndex()) {
            case 0:
                alimentacion = TipoAlimentacion.CARNIVORO;
                especie = new Especie(paisNombre, alimentacion, peso);
                try{
                    Carnivoro carnivoro = new Carnivoro(edad, peso, especie, sector, pais);
                    Controlador.agregarAnimal(carnivoro);
                }catch (java.lang.Exception e){
                }
                break;
            case 1:
                alimentacion = TipoAlimentacion.HERBIVORO;
                especie = new Especie(paisNombre, alimentacion, peso);

                double valorFijo = 0;
                try {
                    String string =textFieldValorFijo.getText();
                    valorFijo = Float.parseFloat(string);
                } catch (Exception e) {
                    valorFijo = 0;
                    e.printStackTrace();
                }
                try{
                    Herbivoro herbivoro = new Herbivoro(edad, peso, especie, sector, valorFijo, pais);
                    Controlador.agregarAnimal(herbivoro);
                    }catch (java.lang.Exception e){
                        e.printStackTrace();
                }
                break;
            case 2:
                alimentacion = TipoAlimentacion.OMNIVORO;
                break;
            default:
                alimentacion = null;
        }
        
        textFieldCodigo.setText("");
        textFieldEdad1.setText("");
        textFieldNombre.setText("");
        textFieldNombrePais1.setText("");
        textFieldPeso.setText("");
        textFieldValorFijo.setText("");
        textFieldValorFijo.setEnabled(false);
    }//GEN-LAST:event_buttonAgregarActionPerformed

    private void buttonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonEliminarActionPerformed

    private void comboBoxAlimentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxAlimentacionActionPerformed
        switch (comboBoxAlimentacion.getSelectedIndex()) {
            case 1:
                textFieldValorFijo.setEnabled(true);
                break;
            default:
                textFieldValorFijo.setEnabled(false);
        }
    }//GEN-LAST:event_comboBoxAlimentacionActionPerformed

    private void textFieldCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCodigoActionPerformed

    private void textFieldValorFijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldValorFijoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldValorFijoActionPerformed

    private void comboBoxSectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxSectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxSectorActionPerformed

    private void textFieldPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldPesoActionPerformed

    private void textFieldEdad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldEdad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldEdad1ActionPerformed

    private void textFieldNombrePais1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNombrePais1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNombrePais1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaAnimalViewModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaAnimalViewModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaAnimalViewModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaAnimalViewModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AltaAnimalViewModel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAgregar;
    private javax.swing.JButton buttonEliminar;
    private javax.swing.JComboBox<String> comboBoxAlimentacion;
    private javax.swing.JComboBox<String> comboBoxSector;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jPeso;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNombre1;
    private javax.swing.JLabel labelNombre2;
    private javax.swing.JTextField textFieldCodigo;
    private javax.swing.JTextField textFieldEdad1;
    private javax.swing.JTextField textFieldNombre;
    private javax.swing.JTextField textFieldNombrePais1;
    private javax.swing.JTextField textFieldPeso;
    private javax.swing.JTextField textFieldValorFijo;
    // End of variables declaration//GEN-END:variables
}
